# Imagen base ligera de Nginx sobre Alpine Linux
FROM nginx:alpine

# Copiar los archivos estáticos (HTML, CSS, JS) al directorio de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80
